spring.application.name=savings-goals-tracker
# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/savings_goals_tracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Zornica255$
logging.level.org.hibernate.persister.entity=ERROR
spring.mvc.hiddenmethod.filter.enabled=true
app.admin.password=admin235
